// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6h5CEDKNqF8FlqrUgxnQkzqx5HRpY9B0',
    appId: '1:95706388458:web:48d8ac3227d333c10e0493',
    messagingSenderId: '95706388458',
    projectId: 'habitect-74f40',
    authDomain: 'habitect-74f40.firebaseapp.com',
    storageBucket: 'habitect-74f40.firebasestorage.app',
    measurementId: 'G-LZTH63DJJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjk9eNydA7Y-hNidy58nAHwZBH0QP_qeQ',
    appId: '1:95706388458:android:a98761a22a1e83d00e0493',
    messagingSenderId: '95706388458',
    projectId: 'habitect-74f40',
    storageBucket: 'habitect-74f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkw3DTbQjLHeqjEjdMIpcvUZox9r1P8iQ',
    appId: '1:95706388458:ios:3e20cf31dcc813d30e0493',
    messagingSenderId: '95706388458',
    projectId: 'habitect-74f40',
    storageBucket: 'habitect-74f40.firebasestorage.app',
    iosBundleId: 'com.example.habitect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkw3DTbQjLHeqjEjdMIpcvUZox9r1P8iQ',
    appId: '1:95706388458:ios:3e20cf31dcc813d30e0493',
    messagingSenderId: '95706388458',
    projectId: 'habitect-74f40',
    storageBucket: 'habitect-74f40.firebasestorage.app',
    iosBundleId: 'com.example.habitect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6h5CEDKNqF8FlqrUgxnQkzqx5HRpY9B0',
    appId: '1:95706388458:web:2d3a957bf379093b0e0493',
    messagingSenderId: '95706388458',
    projectId: 'habitect-74f40',
    authDomain: 'habitect-74f40.firebaseapp.com',
    storageBucket: 'habitect-74f40.firebasestorage.app',
    measurementId: 'G-501TB2KBE7',
  );
}
